language: node_js
node_js: node
script:
  - yarn lint
  - yarn build
branches:
  only:
  - master
after_success:
  - sh .travis/push.sh
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: docs
