version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn build
  release-major:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1a:f6:58:1d:a6:ba:b3:b6:6e:37:69:b7:96:3c:e1:f9"
      - checkout
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: git checkout master && git pull --tags
      - run: yarn cleanup-release:major
      - restore_cache:
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn build
      - run: npm set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > .npmrc
      - run: yarn release:major
  release-minor:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1a:f6:58:1d:a6:ba:b3:b6:6e:37:69:b7:96:3c:e1:f9"
      - checkout
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: git checkout master && git pull --tags
      - run: yarn cleanup-release:minor
      - restore_cache:
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn build
      - run: npm set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: yarn release:minor
  release-patch:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1a:f6:58:1d:a6:ba:b3:b6:6e:37:69:b7:96:3c:e1:f9"
      - checkout
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: git pull --tags
      - run: yarn cleanup-release:patch
      - restore_cache:
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: cache-node-{{ checksum "package.json" }}
      - run: yarn build
      - run: npm set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: yarn release:patch

workflows:
  version: 2
  test:
    jobs:
      - build
      - release-major:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-major$/
      - release-minor:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-minor$/
      - release-patch:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-patch$/
